# Generated by Django 5.1 on 2024-08-10 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Ranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "ranches",
            },
        ),
        migrations.CreateModel(
            name="Cattle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_number", models.CharField(max_length=50, unique=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("entry_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
                (
                    "ranch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.ranch"
                    ),
                ),
            ],
            options={
                "db_table": "cattle",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "cattle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.cattle",
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
            ],
            options={
                "db_table": "subcategories",
                "unique_together": {("category", "name")},
            },
        ),
        migrations.AddField(
            model_name="cattle",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.subcategory"
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("transfer", "Transfer"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "cattle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cattle"
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
