
from django.urls import re_path
from .views import (
    RanchList,
    RanchDetail,
    CategoryList,
    SubcategoryList,
    CattleList,
    cattle_count,
    register_death_api,
    api_death_list ,
    register_sale_api,
    api_sale_list,
    register_recovery_api,
    api_recovery_list,
    register_slaughter_api,
    api_slaughter_list,
    register_transfer_api,
    register_complementary_api,
    register_cattle_api,
    register_bought_api,
    register_new_birth_api,
    add_ranch_api,
    register_lost_api,
    api_complementary_list,
    api_bought_list,
    api_birth_list,
    api_lost_list,
    api_transferred_list,
    api_cattle_list,
    api_cattle_details_list
)

urlpatterns = [
    re_path(r'^ranches/$', RanchList.as_view(), name='ranch_listed'),
    re_path(r'^ranches/(?P<ranch_id>\d+)/$', RanchDetail.as_view(), name='ranch_detail'),
    re_path(r'^categories/$', CategoryList.as_view(), name='category_list'),
    re_path(r'^subcategories/$', SubcategoryList.as_view(), name='subcategory_list'),
    re_path(r'^cattle/$', CattleList.as_view(), name='cattle-list'),
    re_path(r'^cattle-count/$', cattle_count, name='cattle-count'),
    re_path(r'^register-death/$', register_death_api, name='register_death_api'),
    re_path(r'^death-list/$', api_death_list, name='api_death_list'),
    re_path(r'^register-sale/$', register_sale_api, name='register-sale'),
    re_path(r'^sale-list/$', api_sale_list, name='api_sale_list'),
    re_path(r'^register-recovery/$', register_recovery_api, name='api-register-recovery'),
    re_path(r'^recovery-list/$', api_recovery_list, name='api_recovery_list'),
    re_path(r'^register-slaughter/$', register_slaughter_api, name= 'register_slaughter_api'),
    re_path(r'^slaughter-list/$', api_slaughter_list, name= 'api_slaughter_list'),
    re_path(r'^register-transfer/$', register_transfer_api, name= 'register_transfer_api'),
    re_path(r'^register-complementary/$', register_complementary_api, name= 'register_complementary_api'),
    re_path(r'^register-cattle/$', register_cattle_api, name= 'register_cattle_api'),
    re_path(r'^register-bought/$', register_bought_api, name= 'register_bought_api'),
    re_path(r'^register-new-birth/$', register_new_birth_api, name= 'register_new_birth_api'),
    re_path(r'^add-ranch/$', add_ranch_api, name= 'add_ranch_api'),
    re_path(r'^register-lost/$', register_lost_api, name= 'register_lost_api'),
    re_path(r'^complementary-list/$', api_complementary_list, name= 'api_complementary_list'),
    re_path(r'^bought-list/$', api_bought_list, name= 'api_bought_list'),
    re_path(r'^birth-list/$', api_birth_list, name= 'api_birth_list'),
    re_path(r'^lost-list/$', api_lost_list, name= 'api_lost_list'),
    re_path(r'^transferred-list/$', api_transferred_list, name= 'api_transferred_list'),
    re_path(r'^cattle-list/$', api_cattle_list, name= 'api_cattle_list'),
    re_path(r'^details-list/(?P<tag_number>\w+)/$', api_cattle_details_list, name='api_cattle_details_list'),
]
 